env:
  RUST_STABLE_VER: "1.87"

name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: test and lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust ${{ env.RUST_STABLE_VER }}
        run: rustup toolchain install ${{ env.RUST_STABLE_VER }}

      - name: Run cargo fmt
        run: cargo fmt --all --check

      - name: Restore cache
        uses: Swatinem/rust-cache@v2

      - name: Run cargo clippy
        run: cargo clippy --locked -- -D warnings

      - name: Run cargo test
        run: cargo test
