env:
  RUST_STABLE_VER: "1.87"

name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust ${{ env.RUST_STABLE_VER }}
        run: rustup toolchain install ${{ env.RUST_STABLE_VER }}

      - name: Restore cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release

      - name: Create release
        run: |
          gh release create "$TAG" \
            ./target/release/nickel-customs#nickel-customs \
            --title "Release $TAG" \
            --notes "Automated release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}

      - name: Upload
        run: |
          gh release upload "$TAG" target/release/nickel-customs#nickel-customs --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
